### ISSUE TITLE
关闭 Sentinel Filter导致 dubbo.consumer.check=false失效

### ISSUE THREAD

**Issue by xianwei** [dubbo/dubbo-sentinel-support#6]
关闭 Sentinel Filter导致 dubbo.consumer.check=false失效
`
<dubbo:consumer filter="-sentinel.dubbo.consumer.filter"/>`

Sentinel版本 1.8.4
Dubbo版本  2.6.5

**Comment by AlbumenJ** [comment]
Dubbo 2.6.5 已经 EOL 了，升级到 Dubbo 最新版本看看

**Comment by xianwei** [comment]
问题解决了，增加sentinel-dubbo-adapter依赖就好了，表面原因看起来是如果有不存在的filter，consumer的配置都会失效，不知道是不是bug
